### ISSUE TITLE
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'BilateralSliceApply' with these attrs.  Registered devices: [CPU], Registered kernels:   device='GPU' 

### ISSUE THREAD

**Issue by Zealoe** [mgharbi/hdrnet_legacy#11]
I have trouble training the network.
cudnn 5.1.0   tensorflow-gpu 1.1.0   
how can i fix it?
Thanks

[1010] INFO train.py:113 | Adding 2 update ops
2017-09-11 23:24:52.279962: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-11 23:24:52.279988: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-11 23:24:52.280004: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-11 23:24:52.280007: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-11 23:24:52.280010: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-09-11 23:24:56.351927: E tensorflow/stream_executor/cuda/cuda_driver.cc:405] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2017-09-11 23:24:56.352006: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: im-gpuws01
2017-09-11 23:24:56.352018: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: im-gpuws01
2017-09-11 23:24:56.352081: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 375.66.0
2017-09-11 23:24:56.352141: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.66  Mon May  1 15:29:16 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
"""
2017-09-11 23:24:56.352180: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 375.66.0
2017-09-11 23:24:56.352191: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 375.66.0
Traceback (most recent call last):
  File "/home/rox/hdrnet-master/hdrnet/bin/train.py", line 259, in <module>
    main(args, model_params, data_params)
  File "/home/rox/hdrnet-master/hdrnet/bin/train.py", line 150, in main
    with sv.managed_session(config=config) as sess:
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 960, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 788, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 949, in managed_session
    start_standard_services=start_standard_services)
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 706, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 262, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'BilateralSliceApply' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

         [[Node: eval/inference/output/slice/BilateralSliceApply = BilateralSliceApply[has_offset=true, _device="/device:GPU:0"](eval/inference/output/slice/Reshape, eval/inference/guide/Squeeze, train_data/shuffle_batch)]]

Caused by op u'eval/inference/output/slice/BilateralSliceApply', defined at:
  File "/home/rox/hdrnet-master/hdrnet/bin/train.py", line 259, in <module>
    main(args, model_params, data_params)
  File "/home/rox/hdrnet-master/hdrnet/bin/train.py", line 105, in main
    model_params, is_training=False)
  File "/home/rox/hdrnet-master/hdrnet/models.py", line 60, in inference
    fullres_input, guide, bilateral_coeffs)
  File "/home/rox/hdrnet-master/hdrnet/models.py", line 200, in _output
    out = bilateral_slice_apply(coeffs, guide, im, has_offset=True, name='slice')
  File "/home/rox/hdrnet-master/hdrnet/layers.py", line 147, in bilateral_slice_apply
    sliced = hdrnet_ops.bilateral_slice_apply(grid, guide, input_image, has_offset=has_offset)
  File "<string>", line 82, in bilateral_slice_apply
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/rox/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'BilateralSliceApply' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

         [[Node: eval/inference/output/slice/BilateralSliceApply = BilateralSliceApply[has_offset=true, _device="/device:GPU:0"](eval/inference/output/slice/Reshape, eval/inference/guide/Squeeze, train_data/shuffle_batch)]]

**Comment by Zealoe** [comment]
@mgharbi    could you help me ?Thanks

**Comment by Zealoe** [comment]
I have gpu environment and surely have read  https://github.com/mgharbi/hdrnet_legacy/issues/5#issuecomment-323860996.
but i still can not fix my problem.

**Comment by cchen156** [comment]
@Zealoe Did you solve the problem? I meet the same problem.
