### ISSUE TITLE
Shape mismatch during training

### ISSUE THREAD

**Issue by themetaschemer** [mgharbi/hdrnet_legacy#23]
Hi,

I'm trying to train an hdrnet model using your wonderful software with my own dataset, but I'm repeatedly running into the following error (full stack trace below): 

InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [1024,796,3] vs. shape[1] = [2304,1791,3]
	 [[Node: train_data/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](train_data/normalize_images/div, train_data/normalize_images/div_1, train_data/concat/axis)]]

I'm not sure what this error stems from. At first I thought maybe it is due to a mismatch in the input/output image sizes, but I have verified that to not be the case. Is there some requirement of the input/output images that my dataset does not meet? 

Thanks!

Full stack trace: 
`/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[7722] INFO train.py:51 | Preparing summary and checkpoint directory paperculture_data/tr-soojin-1
[7722] INFO train.py:112 | Adding 0 update ops
No regularization.
2018-05-01 17:45:31.163192: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-01 17:45:31.163225: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-01 17:45:31.268284: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-05-01 17:45:31.268634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties:
name: Quadro M4000
major: 5 minor: 2 memoryClockRate (GHz) 0.7725
pciBusID 0000:00:05.0
Total memory: 7.93GiB
Free memory: 7.62GiB
2018-05-01 17:45:31.268659: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0
2018-05-01 17:45:31.268668: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y
2018-05-01 17:45:31.268675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro M4000, pci bus id: 0000:00:05.0)
[7722] INFO train.py:43 | Step 1 | loss = 0.0609 | psnr = -0.0 dB
[7722] INFO train.py:43 | Step 1 | loss = 0.0609 | psnr = -0.0 dB
Traceback (most recent call last):
  File "./hdrnet/bin/train.py", line 270, in <module>
    main(args, model_params, data_params)
  File "./hdrnet/bin/train.py", line 195, in main
    sv.request_stop()
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 960, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 788, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1024,796,3] vs. shape[1] = [2304,1791,3]
	 [[Node: train_data/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](train_data/normalize_images/div, train_data/normalize_images/div_1, train_data/concat/axis)]]

Caused by op u'train_data/concat', defined at:
  File "./hdrnet/bin/train.py", line 270, in <module>
    main(args, model_params, data_params)
  File "./hdrnet/bin/train.py", line 74, in main
    output_resolution=args.output_resolution)
  File "/home/paperspace/work/hdrnet/hdrnet/data_pipeline.py", line 100, in __init__
    sample = self._produce_one_sample()
  File "/home/paperspace/work/hdrnet/hdrnet/data_pipeline.py", line 234, in _produce_one_sample
    inout = tf.concat([im_input, im_output], 2)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1034, in concat
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 519, in _concat_v2
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [1024,796,3] vs. shape[1] = [2304,1791,3]
	 [[Node: train_data/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](train_data/normalize_images/div, train_data/normalize_images/div_1, train_data/concat/axis)]]
`

**Comment by themetaschemer** [comment]
Closing this issue -- I found an image that had mismatched input/output dimensions.
