### ISSUE TITLE
BilateralSliceApply error when trying to convert to TensorFlow Lite

### ISSUE THREAD

**Issue by sis00308** [mgharbi/hdrnet_legacy#48]
Hi, I've been encountering this error when trying to convert hdrnet using TensorFlow Lite : 

`
tflite_convert --saved_model_dir ~/hdrnet/pretrained_models/hdrp_mod/tmp/ --output_file ~/hdrnet/pretrained_models/hdrp_mod/tmp/hdrp_mod.tflite --enable_v1_converter
2020-02-07 13:29:47.947001: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-07 13:29:47.997959: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-07 13:29:47.998320: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: GeForce 940M major: 5 minor: 0 memoryClockRate(GHz): 1.176
pciBusID: 0000:01:00.0
totalMemory: 1.96GiB freeMemory: 1.67GiB
2020-02-07 13:29:47.998352: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2020-02-07 13:29:48.706501: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-07 13:29:48.706538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2020-02-07 13:29:48.706546: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2020-02-07 13:29:48.706687: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1419 MB memory) -> physical GPU (device: 0, name: GeForce 940M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Traceback (most recent call last):
  File "~/.local/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 370, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "~/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 366, in run_main
    _convert_model(tflite_flags)
  File "~/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 94, in _convert_model
    converter = _get_toco_converter(flags)
  File "~/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 81, in _get_toco_converter
    return converter_fn(**converter_kwargs)
  File "~/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/lite.py", line 268, in from_saved_model
    output_arrays, tag_set, signature_key)
  File "~/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/convert_saved_model.py", line 239, in freeze_saved_model
    meta_graph = _get_meta_graph_def(saved_model_dir, tag_set)
  File "~/.local/lib/python3.5/site-packages/tensorflow/contrib/lite/python/convert_saved_model.py", line 61, in _get_meta_graph_def
    return loader.load(sess, tag_set, saved_model_dir)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/saved_model/loader_impl.py", line 212, in load
    return loader.load(sess, tags, import_scope, **saver_kwargs)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/saved_model/loader_impl.py", line 365, in load
    **saver_kwargs)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/saved_model/loader_impl.py", line 293, in load_graph
    meta_graph_def, import_scope=import_scope, **saver_kwargs)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1939, in import_meta_graph
    **kwargs)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 744, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 391, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "~/.local/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 158, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'BilateralSliceApply'
`

Is this because hdrnet was built using TensorFlow 1.1, and minimum TensorFlow version required for TensorFlow Lite conversion is TensorFlow 1.9? Or is this due to custom operation not being supported on mobile?

**Comment by mgharbi** [comment]
This is most likely the case yes, I have never used this code base with TFLite. You might need to provide / compile a custom op implementation for TFLite.
